### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by choigicheol** [choigicheol/sameMate#1]
- [ ] 회원가입 완료 시 로그인화면으로 이동할때 => 회원가입이 완료되었습니다 모달 띄우기
- [ ] 일반로그인 재실행 시 자동 로그인 안됨
- [ ] 로그인화면에서 로그인버튼이 키보드에 가려져 불편한거같다 위치 수정
- [ ] Seach, Mypage 스크린 에서도 포스터 터치 시 상세정보 볼 수 있게 변경
- [x] modal 외부 터치 시 창 닫히게 하기
- [x] 로그인 후 Home 스크린에서 뒤로가기 버튼 터치 시 로그인 상태임에도 Login 스크린으로 이동하는 문제 수정
---
## 시간이 좀 필요할 것 같은 작업

- [ ] 메인 카테고리 추가(TV) - TMDB API 이용
- [ ] 메인 카테고리 추가 (도서(만화책)) - 카카오 도서 검색 API (도서와 만화책 분리 할 수 있을까 고민해보기)
- [ ] 메인 카테고리 추가(음악) - 아직 안찾아봄
- [x] Home 스크린에서 일치 갯수에 따라 추천목록 필터 가능한 기능 추가
- [ ] Home 스크린 추천목록 부분 무한 스크롤로 변경
---
